### ISSUE TITLE
non-configurable timeouts

### ISSUE THREAD

**Issue by KyleSanderson** [buroa/qbtools#1]
10:03:19 PM WARNING:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='qbittorrent', port=8080): Read timed out. (read timeout=15.1)")': /10:03:50 PM WARNING:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='qbittorrent', port=8080): Read timed out. (read timeout=15.1)")': /10:04:35 PM WARNING:Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbaef8b8400>, 'Connection to qbittorrent timed out. (connect timeout=15.1)')': /

**Comment by onedr0p** [comment]
Any more information on how you ran this? like what app options? what container options? That debug message isn't really helpful  and there's nothing to go off of in trying to reproduce that error.

**Comment by KyleSanderson** [comment]
I have session logon enabled, and my qBittorrent instances take anywhere from 500ms to 300 seconds to login and return the list. In the meanwhile, if another client logs in to qBittorrent, it will invalidate the old session, resulting in that other client having to login once more.

**Comment by onedr0p** [comment]
Up to 300 seconds to return the torrents!? I think there's another problem happening.

**Comment by KyleSanderson** [comment]
> Up to 300 seconds to return the torrents!? I think there's another problem happening.

well yeah, it's bad software haha. They've put in optimizations in later versions but the resident set is atleast 2x what it was. Anyway, was hoping this was a true fork. if not that's fine.

**Comment by buroa** [comment]
> > Up to 300 seconds to return the torrents!? I think there's another problem happening.
> 
> 
> 
> well yeah, it's bad software haha. They've put in optimizations in later versions but the resident set is atleast 2x what it was. Anyway, was hoping this was a true fork. if not that's fine.

Does the upstream qbittools have this fixed?

**Comment by KyleSanderson** [comment]
> > > Up to 300 seconds to return the torrents!? I think there's another problem happening.
> > 
> > 
> > well yeah, it's bad software haha. They've put in optimizations in later versions but the resident set is atleast 2x what it was. Anyway, was hoping this was a true fork. if not that's fine.
> 
> Does the upstream qbittools have this fixed?

please see the very first line in your readme.md 😄

**Comment by buroa** [comment]
> > > > Up to 300 seconds to return the torrents!? I think there's another problem happening.
> 
> > > 
> 
> > > 
> 
> > > well yeah, it's bad software haha. They've put in optimizations in later versions but the resident set is atleast 2x what it was. Anyway, was hoping this was a true fork. if not that's fine.
> 
> > 
> 
> > Does the upstream qbittools have this fixed?
> 
> 
> 
> please see the very first line in your readme.md 😄 

That wasn't the question. Is it fixed upstream?

**Comment by KyleSanderson** [comment]
> > > > > Up to 300 seconds to return the torrents!? I think there's another problem happening.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > well yeah, it's bad software haha. They've put in optimizations in later versions but the resident set is atleast 2x what it was. Anyway, was hoping this was a true fork. if not that's fine.
> > 
> > 
> > > 
> > 
> > 
> > > Does the upstream qbittools have this fixed?
> > 
> > 
> > please see the very first line in your readme.md 😄
> 
> That wasn't the question. Is it fixed upstream?

Of course not 😕

**Comment by buroa** [comment]
> > > > > > Up to 300 seconds to return the torrents!? I think there's another problem happening.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > well yeah, it's bad software haha. They've put in optimizations in later versions but the resident set is atleast 2x what it was. Anyway, was hoping this was a true fork. if not that's fine.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Does the upstream qbittools have this fixed?
> 
> > > 
> 
> > > 
> 
> > > please see the very first line in your readme.md 😄
> 
> > 
> 
> > That wasn't the question. Is it fixed upstream?
> 
> 
> 
> Of course not 😕 

Okay, do you just require longer timeouts to resolve your issue?

**Comment by KyleSanderson** [comment]
and a simple retry for when the session becomes invalided, yes.

**Comment by onedr0p** [comment]
Kyle your whole demeanor is strange here. Something is very off on your end if qb is taking 5 minutes to return a list of torrents. Also @buroa and I disable qb authentication since it's only deployed internally so we don't run into the problem of sessions getting invalidated.

**Comment by KyleSanderson** [comment]
Yeah it's ok, the majority of products suffer from this. I've moved to running my own thing (I think it's at an hour of effort now), and don't want to waste your time.
