### ISSUE TITLE
Expired argument

### ISSUE THREAD

**Issue by MrMarble** [buroa/qbtools#10]
Great addition! 

Would be nice to be able to just add a tag once the time/ratio is met, instead of removing the torrent directly, just to know that you're safe to remove it if you want, most trackers give you extra points the longer you share a torrent, so having that option would be awesome.

Now that the tracker names are configured, maybe using them to tag the torrents is useful? Like https://github.com/StuffAnThings/qbit_manage does

Also, it is ok if I make a PR adding more trackers? Most of them are for Spanish content, I don't use any of the already configured :(

**Comment by buroa** [comment]
@MrMarble I'm going to make some type of configuration file so users can change how long they want to seed for which trackers, etc.

And PR's are of course welcome!

**Comment by onedr0p** [comment]
I think an `expired` tag, with maybe a `--tag-only` arg instead of deleting is a wonderful idea! And yes, please add more indexers. I only added the ones I am familiar with.

**Comment by onedr0p** [comment]
On second thought I think we should default to tagging with `expired` tag and add in a `--delete` arg to delete them instead.

**Comment by onedr0p** [comment]
@MrMarble `--delete` arg added to expired in  https://github.com/buroa/qbittools/releases/tag/v0.6.2

Without setting that flag the torrent will just be given a `expired` tag.

**Comment by MrMarble** [comment]
I noticed that the seeding time for `avistaz` is not quite right, they use this chart: 
![dAuNlTiF_o](https://github.com/buroa/qbittools/assets/4268580/602260aa-25f8-4478-b645-e9721da30b0a)

There's a formula, in case you want to use it lol
![QoLBr9Xe_o](https://github.com/buroa/qbittools/assets/4268580/a1fba959-6033-41f9-9488-1fecf4b0e736)


It is the same for avistaz, cinemaz and exoticaz.

**Comment by onedr0p** [comment]
To not complicate things I kept those 10 days. It's pretty rare to download something over 100GB on those trackers 🙂

**Comment by MrMarble** [comment]
> To not complicate things I kept those 10 days. It's pretty rare to download something over 100GB on those trackers 🙂

That's what I thought, I pointed it out just in case

**Comment by onedr0p** [comment]
So I'm thinking most of the expired logic can be moved to the tagging command, and the expired command can just delete any torrents with the expired tag. That makes it so the tracker list is contained to only one command.

**Comment by onedr0p** [comment]
Just released v0.7.0 with that logic, gonna close this issue now.
