### ISSUE TITLE
Orphaned logic not taking in account folders

### ISSUE THREAD

**Issue by MrMarble** [buroa/qbtools#15]
Tried running `orphaned` command in `dry-run` mode and got a lot of logs skipping some files which are being downloaded, looking further into it, all the files are inside a parent folder.

```
09:11:32 AM INFO:The flag --dry-run is set, skipping item /media/Downloads/qbittorrent/complete/downloads/Captain Ultra/Captain Ultra - 16 [WEB-DL][480p][671B07CE].mkv...
09:11:32 AM INFO:The flag --dry-run is set, skipping item /media/Downloads/qbittorrent/complete/downloads/Captain Ultra/Captain Ultra - 22 [WEB-DL][480p][7A4CBD26].mkv...
09:11:32 AM INFO:The flag --dry-run is set, skipping item /media/Downloads/qbittorrent/complete/downloads/Captain Ultra/Captain Ultra - 14 [WEB-DL][480p][82FBEC2C].mkv...
09:11:32 AM INFO:The flag --dry-run is set, skipping item /media/Downloads/qbittorrent/complete/downloads/Captain Ultra/Captain Ultra - 07 [WEB-DL][480p][6DF849A4].mkv...
09:11:32 AM INFO:The flag --dry-run is set, skipping item /media/Downloads/qbittorrent/complete/downloads/Captain Ultra/Captain Ultra - 19 [WEB-DL][480p][8BC33E30].mkv...
09:11:32 AM INFO:The flag --dry-run is set, skipping item /media/Downloads/qbittorrent/complete/downloads/Captain Ultra/Captain Ultra - 24 [WEB-DL][480p][8897EC1B].mkv...
....
```

qbtools uses the `content_path` attribute to get the torrent file
https://github.com/buroa/qbittools/blob/abf7aee16adfd549390b73527da2eac72c08565f/qbittools/commands/orphaned.py#L21
but that attribute only returns the top most directory:
```jsonc
// `/api/v2/torrents/info` response of one of the mentioned torrents
{
		"hash": "e7ddc3e750472a5a4e9d2239477998bcf0008708",
		"save_path": "/media/Downloads/qbittorrent/complete/downloads",
		"content_path": "/media/Downloads/qbittorrent/complete/downloads/Captain Ultra",
		...
}
```

if the `content_path` is a directory, it is added to the list of filest directly:
https://github.com/buroa/qbittools/blob/abf7aee16adfd549390b73527da2eac72c08565f/qbittools/commands/orphaned.py#L30-L31

but then, when checked with the disks files, does not match (see the snippet in the screenshot):
https://github.com/buroa/qbittools/blob/abf7aee16adfd549390b73527da2eac72c08565f/qbittools/commands/orphaned.py#L42

![imagen](https://github.com/buroa/qbittools/assets/4268580/d53868c3-f4d0-4370-b79b-bc4c468e4517)

---

This could be solved by traversing the directory and adding all the files instead of the parent folder or by using the `files` endpoint which returns a list of all the files inside the torrent.

**Comment by onedr0p** [comment]
The orphaned command is a bit opinionated on having a certain folder structure as it is pretty hard to support all different variations of folder structures. Let me walk a bit thru my set up...

<img width="686" alt="image" src="https://github.com/buroa/qbittools/assets/213795/897adebf-7689-4e5a-a569-9bfd129cbd01">

1. `Pre-allocate disk space for all files` should not be set if downloading to a CoW filesystem like ZFS.
2. My default save path is set to `/media/Downloads/qbittorrent/complete`
3. The incomplete dir should be set to a path outside that dir e.g. `/media/Downloads/qbittorrent/incomplete` or how I have it `/incomplete` (which is an `emptyDir` in my Kubernetes config).
4. Each category you create should have save path of a subdir of the default save path `/media/Downloads/qbittorrent/complete/$category`

<img width="415" alt="image" src="https://github.com/buroa/qbittools/assets/213795/aa8474ff-dc15-4994-a392-b80c06fbb8f2">


With that said, in your setup is the downloads dir in `/media/Downloads/qbittorrent/complete/downloads/` a category in qbittorrent? Would it be possible to set up your qB config like I explained above? We are open to PRs but this code in `orphaned` can get quite messy and hard to test when we start to account for all different variations of folder structures.

**Comment by MrMarble** [comment]
> The orphaned command is a bit opinionated on having a certain folder structure as it is pretty hard to support all different variations of folder structures. Let me walk a bit thru my set up...
> 
> <img width="686" alt="image" src="https://github.com/buroa/qbittools/assets/213795/897adebf-7689-4e5a-a569-9bfd129cbd01">
> 
> 1. `Pre-allocate disk space for all files` should not be set if downloading to a CoW filesystem like ZFS.
> 2. My default save path is set to `/media/Downloads/qbittorrent/complete`
> 3. The incomplete dir should be set to a path outside that dir e.g. `/media/Downloads/qbittorrent/incomplete` or how I have it `/incomplete` (which is an `emptyDir` in my Kubernetes config).
> 4. Each category you create should have save path of a subdir of the default save path `/media/Downloads/qbittorrent/complete/$category`
> 
> <img width="415" alt="image" src="https://github.com/buroa/qbittools/assets/213795/aa8474ff-dc15-4994-a392-b80c06fbb8f2">
> 
> 
> With that said, in your setup is the downloads dir in `/media/Downloads/qbittorrent/complete/downloads/` a category in qbittorrent? Would it be possible to set up your qB config like I explained above? We are open to PRs but this code in `orphaned` can get quite messy and hard to test when we start to account for all different variations of folder structures.
> 

I have exactly that configuration (you helped me set everything up a while ago on discord)

The problem is when the torrent is a folder containing multiple files (the one used in the example is a season of a tv show), not related to the qb configuration 

I'm not at home now, here's a screenshot of the torrent's files

![Screenshot_2023-08-27-14-39-28-763_me.fengmlo.qbRemoteFree.jpg](https://github.com/buroa/qbittools/assets/4268580/f8f6c62a-d8bc-479c-bf2e-7d27c9a7233e)

**Comment by onedr0p** [comment]
Oh nice! however it doesn't look like you are using categories and category subfolder off of `/media/Downloads/qbittorrent/complete` ?

This does work for me and @buroa so something appears a bit off.

**Comment by onedr0p** [comment]
Closing this issue, it was due to the orphaned command expecting all torrents to be in a category in qb and in a subfolder under complete dir matching the category name. Which was not the case here.
