### ISSUE TITLE
Queued torrents are being reannounced

### ISSUE THREAD

**Issue by catch-404** [buroa/qbtools#51]
Torrents that are waiting in queue are being reannounced constantly. They are seen as active for 0s throughout. As a result, they are often force-started, resulting in stalling torrents that were previously downloading (and were thus higher in the queue). 

I think it would be beneficial to have an exception for queuing torrents. There's no point in reannouncing those.

For reference, the logs were showing this line every 5 seconds until the torrent was forced to start: 
`12:49:46 PM INFO:[some_torrent_redacted] is not working, active for 0s, reannouncing...`

**Comment by buroa** [comment]
You are free to open a PR if you believe this is a problem on your end.

**Comment by catch-404** [comment]
I don't have the technical knowledge to know how to change this behaviour. I'm just letting you know in case you think that change would make sense.

**Comment by buroa** [comment]
@catch-404 Torrents will not be started (nor force-started) via the announcement process unless you are using `--pause-resume`. If you are, try removing that flag and see what happens.

**Comment by catch-404** [comment]
I'm not using the flag, and I noticed a number of torrents acting this way (being started). I'm not sure what exactly is happening, but I assumed at some point qbittorrent would start prioritizing the torrent over others higher in the queue because of the number of announces in a short amount of time. 

In any case, the fact that the torrent starts isn't the core of the issue imo. It's the fact that a queued torrent would hammer the tracker with announces every 5 seconds with no failsafe, since qbitools keeps seeing it as "active for 0s" throughout. 

If anything, the fact that those torrents end up starting at some point is actually a better outcome than them keeping hammering their tracker until they move up the queue and it's their time to start downloading. 

Hence why I think it would make sense to exclude queued torrents from the reannounce command.

**Comment by catch-404** [comment]
I did some more testing, so just to follow-up: 

This behaviour seems to be triggered when the tracker status is "not contacted yet". It also happens with torrents that are checking. From what I can tell, qbitools isn't actually announcing anything to trackers in that situation (the trackers are never actually updating), but it seems to believe it does (as we can see from the logs). 

Might be a non-issue after all, I'll let you be the judge of that. Might still be useful to make the reannounce command understand that queued and checking torrents are actually paused; I feel like that's the core of the issue, but again, really not sure about it.

**Comment by buroa** [comment]
@catch-404 I updated the renouncement logic. Please let me know if this works for you.
