### ISSUE TITLE
The `orphaned`, `prune` and `tagging` commands should logout (clear session) of qb

### ISSUE THREAD

**Issue by onedr0p** [buroa/qbtools#68]
When these 3 commands have ran and are done before exit they should call https://qbittorrent-api.readthedocs.io/en/v2024.9.67/apidoc/auth.html#qbittorrentapi.auth.Authorization.log_out to clear the session, otherwise qb will not free up memory on these sessions. Without this qb memory will grow overtime. See below

https://github.com/qbittorrent/qBittorrent/issues/18830#issuecomment-1510423845

---

Re-announce script _should_ be fine as is but it wouldn't hurt to add a logout when the script is killed.

**Comment by buroa** [comment]
Closed with https://github.com/buroa/qbtools/commit/929b8fc1bf8f014323552219144fe4820692446e
