### ISSUE TITLE
qbtools requires /config/config.yaml

### ISSUE THREAD

**Issue by joryirving** [buroa/qbtools#70]
In the new `v0.17.3` release, it assumes/requires `/config/config.yaml`. This wasn't the case in `v0.17.2`. I'm only using qbtools to reannounce, so I don't have/use a config file.

If the file is required now, would it be possible to get a copy of a dummy file?

Relevant hr:
https://github.com/joryirving/home-ops/blob/93d68062ea0d8e6a09dbe85ebc56611192215d4c/kubernetes/main/apps/downloads/qbittorrent/tools/helmrelease.yaml

**Comment by buroa** [comment]
Pull the latest hash of v0.17.3; this was a bad release and reverted within the hour.
